### ISSUE TITLE
cant  run with options 

### ISSUE THREAD

**Issue by arnitkun** [innovationgarage/label-V#4]
specifying options in the terminal doesn't lead to expected results.  I am certainly missing something.

Also is it possible to generate annotations directly from the browser UI?

I wonder if the tracking can be extended to more than 4 boxes.

Physical Ubuntu 16, firefox, python 2.7

**Comment by redhog** [comment]
As for the terminal options, could you supply a command line and error output?

Wrt the web UI, do you mean to download the generated annotations directly from the UI, rather than copy them from disk? If so the answer is no - right now all the annotations are saved on disk in the "upload" folder. labelv/convert.py can help you convert this data to a simple (flat) numpy file.

In the web version there is no limit on number of boxes, or their grouping. Generally, you don't want to track a single object using only one box, as that often leads to the box drifting/deforming, esp if the camera pans/rotates. Instead you can use the grouping feature, where you mark some conspicuous features of the object, and then group those boxes and label the group. The output will be both the bboxes for each feature, and a bbox for the group. If the camera pans, and the features gets closer together and then further apart from each other, the group will shrink and then grow to encompass the grouped feature boxes.

Hope this explanation helps a bit!

**Comment by arnitkun** [comment]
I'm trying to supply the arguments to labelv-service in bash, which I think is wrong. So I guess I could just use the default settings and paths.

Sorry for bothering you on this completely unrelated topic, but it is possible to get coco-like annotations out of this. right? I am confused.

**Comment by redhog** [comment]
There's no way right now to get exactly the format needed by coco. However you can get a very simple csv-based "flat" output that would be easy to convert to whatever you need by running `labelv/convert.py VIDEO_ID SESSION_ID` (this so should be installed by setup.py, but it isn't). Feel free to hack that script/make another one that has coco formatted output and make a PR!
